### PR TITLE
Object detection update

### PR DESCRIPTION
**Pull request by kini5gowda**
Getting bugs with respect to depth camera. The rest works perfectly fine. I have commented out the 2d to 3d part. Will have to figure out the depth camera part.

### CODE REVIEW

**Comment by LiamWellacott** [comment]
@kini5gowda if this depends on your previous PR I will wait for that to go through before reviewing, see my comment on that about merging.

**Comment by kini5gowda** [comment]
Nope, doesnt depend on the previous one. I've removed the previous pull
request and started a new one.

**Comment by LiamWellacott** [comment]
please merge with my main then I will review this.

**Comment by LiamWellacott** [comment]
After chatting to Pierre this is not ready to come back to main, the dockerfile command doesn't work currently and apparently there is outstanding work to get DOPE working. We will reopen when the code is ready.

**Pull request closed without merging**
